// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: notify/notify.proto

package notify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotifierClient is the client API for Notifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifierClient interface {
	Notify(ctx context.Context, opts ...grpc.CallOption) (Notifier_NotifyClient, error)
}

type notifierClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifierClient(cc grpc.ClientConnInterface) NotifierClient {
	return &notifierClient{cc}
}

func (c *notifierClient) Notify(ctx context.Context, opts ...grpc.CallOption) (Notifier_NotifyClient, error) {
	stream, err := c.cc.NewStream(ctx, &Notifier_ServiceDesc.Streams[0], "/notify.Notifier/Notify", opts...)
	if err != nil {
		return nil, err
	}
	x := &notifierNotifyClient{stream}
	return x, nil
}

type Notifier_NotifyClient interface {
	Send(*NotificationRequest) error
	CloseAndRecv() (*NotificationResponse, error)
	grpc.ClientStream
}

type notifierNotifyClient struct {
	grpc.ClientStream
}

func (x *notifierNotifyClient) Send(m *NotificationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *notifierNotifyClient) CloseAndRecv() (*NotificationResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(NotificationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotifierServer is the server API for Notifier service.
// All implementations must embed UnimplementedNotifierServer
// for forward compatibility
type NotifierServer interface {
	Notify(Notifier_NotifyServer) error
	mustEmbedUnimplementedNotifierServer()
}

// UnimplementedNotifierServer must be embedded to have forward compatible implementations.
type UnimplementedNotifierServer struct {
}

func (UnimplementedNotifierServer) Notify(Notifier_NotifyServer) error {
	return status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedNotifierServer) mustEmbedUnimplementedNotifierServer() {}

// UnsafeNotifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifierServer will
// result in compilation errors.
type UnsafeNotifierServer interface {
	mustEmbedUnimplementedNotifierServer()
}

func RegisterNotifierServer(s grpc.ServiceRegistrar, srv NotifierServer) {
	s.RegisterService(&Notifier_ServiceDesc, srv)
}

func _Notifier_Notify_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NotifierServer).Notify(&notifierNotifyServer{stream})
}

type Notifier_NotifyServer interface {
	SendAndClose(*NotificationResponse) error
	Recv() (*NotificationRequest, error)
	grpc.ServerStream
}

type notifierNotifyServer struct {
	grpc.ServerStream
}

func (x *notifierNotifyServer) SendAndClose(m *NotificationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *notifierNotifyServer) Recv() (*NotificationRequest, error) {
	m := new(NotificationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Notifier_ServiceDesc is the grpc.ServiceDesc for Notifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notify.Notifier",
	HandlerType: (*NotifierServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Notify",
			Handler:       _Notifier_Notify_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "notify/notify.proto",
}
