FROM influxdb:2.4.0-alpine
# PYTHON3 & FLASK
RUN ["apk", "update"]
RUN ["apk", "upgrade"]
RUN ["apk", "add", "python3"]
RUN ["apk", "add", "py3-pip"]
RUN ["pip3", "install", "Flask"]
# add application here
